[phases.setup]
nixPkgs = ["python310", "gcc"]

[phases.install]
cmds = ["pip install -r requirements.txt && python -m nltk.downloader punkt stopwords"]

[start]
cmd = "gunicorn app:app --bind 0.0.0.0:$PORT"